language: ruby
sudo: false
cache: bundler
bundler_args: --without development --retry=3 --jobs=3

rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5

matrix:
  allow_failures:
    - 1.9
    - 2.0
    - 2.1
    - ruby-head
  fast_finish: true
